NETVIRT-1675 : Exceptions Multiple entries with same key seen in openflowplugin
		       java.lang.IllegalArgumentException: Multiple entries with same key:
                To index multiple values under a key, use Multimaps.index.
                at com.google.common.collect.Maps.uniqueIndex(Maps.java:1338) ~[?:?]
                at com.google.common.collect.Maps.uniqueIndex(Maps.java:1293) ~[?:?]
                at org.opendaylight.yangtools.yang.binding.CodeHelpers.compatMap(CodeHelpers.java:296) ~[?:?]
                at org.opendaylight.yang.gen.v1.urn.opendaylight.direct.statistics.rev160511.GetFlowStatisticsOutputBuilder.setFlowAndStatisticsMapList(GetFlowStatisticsOutputBuilder.java:133) ~[?:?]

description: Post aluminium mri changes node statistics rpc response was not successful, as flowstatisticsmaplist list contain duplicate flow-Id keys, however as per flowstatisticsmaplist yang definition flow-ik key should be unique else Unique index exception is thrown. Since flow-Id key generated from Elan module are not unique (Elantag+macaddress) for specific flows(related to table50 and table 51) and model definition expects flow-id as a key, exception was thrown. Datamodel opendaylight-flow-statistics.yang modified by removing key flow-id from flowstatisticsmaplist.

Signed-off-by: dheenadayalan b <dhinua@gmail.com>
Change-Id: I014e18630d1531df2f13e4d0c83defa183cadf0d
Signed-off-by: dheenadayalan b <dhinua@gmail.com>