Remove M2E lifecycle-mapping <execute/> for yang-maven-plugin
This appears to be broken anyway (causing:
org.apache.maven.plugin.MojoExecutionException: yang-to-sources: Unable
to parse yang files from
/home/vorburger/dev/ODL/git/openflowplugin/applications/forwardingrules-manager/src/main/yang;
Caused by:
org.opendaylight.yangtools.yang.parser.spi.meta.InferenceException:
Imported module [config] was not found. [at null:6:1])

In https://github.com/vorburger/opendaylight-eclipse-setup, the
workspace wide lifecycle mapping for yang-maven-plugin is ignore.

In the future, I'm hoping that I'll be able to bundle yangide in
opendaylight-eclipse-setup, and it will correctly configure code
generation.

Change-Id: I8c1640482912eb05ea3fb07e9d55d82f90ab6ebd
Signed-off-by: Michael Vorburger <vorburger@redhat.com>